### ISSUE TITLE
Webstorm compatibility

### ISSUE THREAD

**Issue by jbro-io** [jmulieri/front-end-alignment#1]
Any chance you could make this compatible with the IntelliJ Webstorm product?

**Comment by jmulieri** [comment]
Found this post http://confluence.jetbrains.com/display/IDEADEV/Plugin+Compatibility+with+IntelliJ+Platform+Products indicating that without specifying a dependency, only IDEA will be supported. I just added a dependency that seemed innocuous enough and it seems to work without any issues in WebStorm. I submitted the update to the IntelliJ repo and it should be available within 2 days. In the meantime, you can follow the "Installing plugin from jar" instructions contained in the README and try it out before then. Enjoy!

**Comment by jbro-io** [comment]
Works perfectly! Thanks a bunch!!

**Comment by jmulieri** [comment]
Nice! Glad to help!
